name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        fi
        
    - name: Build application
      run: |
        cd ccswitch-mac
        xcodebuild -project ccswitch.xcodeproj \
          -scheme ccswitch \
          -configuration Release \
          -derivedDataPath build \
          -destination 'platform=macOS' \
          build
          
    - name: Create DMG
      run: |
        # 设置版本变量
        VERSION="${{ steps.version.outputs.VERSION }}"
        APP_NAME="CCSwitch"
        BUILD_DIR="$(pwd)/ccswitch-mac/build"
        APP_PATH="${BUILD_DIR}/Build/Products/Release/${APP_NAME}.app"
        
        # 创建分发目录
        mkdir -p dist
        
        # 创建临时 DMG 目录
        TEMP_DMG_DIR="$(pwd)/dmg_temp"
        mkdir -p "${TEMP_DMG_DIR}"
        
        # 复制应用程序
        cp -R "${APP_PATH}" "${TEMP_DMG_DIR}/"
        
        # 创建 Applications 链接
        ln -s /Applications "${TEMP_DMG_DIR}/Applications"
        
        # 创建安装说明
        cat > "${TEMP_DMG_DIR}/安装说明.txt" << 'EOF'
        CCSwitch 安装说明

        由于此应用程序未经 Apple 签名，您需要按照以下步骤进行安装：

        1. 将 CCSwitch.app 拖拽到 Applications 文件夹
        2. 首次运行时，如果系统提示"无法打开"：
           - 按住 Control 键并点击 CCSwitch.app
           - 选择"打开"
           - 在弹出的对话框中点击"打开"

        或者在系统偏好设置 > 安全性与隐私 > 通用中点击"仍要打开"

        项目开源地址: https://github.com/${{ github.repository }}
        EOF
        
        # 创建 DMG
        DMG_PATH="dist/${APP_NAME}-${VERSION}.dmg"
        hdiutil create -srcfolder "${TEMP_DMG_DIR}" \
          -volname "${APP_NAME} ${VERSION}" \
          -fs HFS+ \
          -fsargs "-c c=64,a=16,e=16" \
          -format UDBZ \
          -size 100m \
          "${DMG_PATH}"
          
        # 清理
        rm -rf "${TEMP_DMG_DIR}"
        
        # 输出信息
        echo "DMG_PATH=${DMG_PATH}" >> $GITHUB_ENV
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        
    - name: Calculate checksums
      run: |
        cd dist
        shasum -a 256 *.dmg > checksums.txt
        cat checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: CCSwitch v${{ steps.version.outputs.VERSION }}
        body: |
          ## CCSwitch v${{ steps.version.outputs.VERSION }}
          
          🎉 **新版本发布！**
          
          CCSwitch 是一个帮助您快速切换 Claude Code API 配置的 macOS 菜单栏应用程序。
          
          ### 📥 安装说明
          
          **重要：由于应用程序未经 Apple 签名，请按照以下步骤安装：**
          
          1. 下载 `CCSwitch-${{ steps.version.outputs.VERSION }}.dmg`
          2. 双击挂载 DMG 文件
          3. 将 `CCSwitch.app` 拖拽到 `Applications` 文件夹
          4. 首次运行时：
             - 如果看到"无法打开"的提示，请按住 `Control` 键点击应用程序
             - 选择"打开"，然后在弹出对话框中再次点击"打开"
             - 或者在 `系统偏好设置` > `安全性与隐私` > `通用` 中点击"仍要打开"
          
          ### ✨ 主要功能
          
          - 🔄 快速切换 Claude Code API 配置
          - 🎯 支持多种 API 提供商（官方、Kimi、GAC Code、Anyrouter 等）
          - ⚡ 菜单栏快速访问
          - 🛠 自定义配置管理
          - 🌐 多语言支持（中文、英文）
          - 🚀 开机自启动选项
          
          ### 🔧 系统要求
          
          - macOS 10.15 或更高版本
          - 支持 Intel 和 Apple Silicon Mac
          
          ### 📋 文件校验
          
          请验证下载文件的完整性：
          ```
          shasum -a 256 CCSwitch-${{ steps.version.outputs.VERSION }}.dmg
          ```
          
          ### 🐛 问题反馈
          
          如遇到问题，请在 [GitHub Issues](https://github.com/${{ github.repository }}/issues) 中反馈。
          
          ### 💖 支持项目
          
          如果 CCSwitch 对您有帮助，欢迎通过以下方式支持项目发展：
          
          ☕ **Buy me a coffee**: https://coff.ee/wangrui15f
          
          您的支持将帮助我们：
          - 持续改进和修复 bug
          - 开发更多实用功能
          - 购买 Apple 开发者证书提供签名版本
          
          ⭐ 别忘了给项目点个 Star！
          
        files: |
          dist/*.dmg
          dist/checksums.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}